# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_customer_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='invoice',
            new_name='bills',
        ),
    ]
