# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20170521_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='invoice_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
