# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_bills_invoice_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
        migrations.AddField(
            model_name='bills',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
