# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20170523_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'unknown', max_length=30)),
                ('address', models.CharField(default=b'unknown', max_length=200)),
                ('phone', models.CharField(default=b'unknown', max_length=12)),
                ('email', models.EmailField(default=b'unknown', max_length=50)),
                ('pincode', models.CharField(default=b'0', max_length=6)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice_no', models.IntegerField()),
                ('tax_percent', models.IntegerField()),
                ('discount_percent', models.IntegerField()),
                ('sub_total', models.IntegerField()),
                ('tax_amount', models.IntegerField()),
                ('discount_amount', models.IntegerField()),
                ('grand_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.IntegerField()),
                ('item_no', models.IntegerField()),
                ('item', models.CharField(max_length=300)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='bills',
        ),
        migrations.DeleteModel(
            name='customer',
        ),
    ]
