# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_auto_20170524_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discount_amount',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount_percent',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sub_total',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_amount',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_percent',
            field=models.CharField(max_length=10),
        ),
    ]
